### ISSUE TITLE
Publish to Maven central using sbt-ci-release and groupId `com.github.sbt`

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-sdlc#3]
The artifacts of sbt-sdlc are only available on repo.scala-sbt.org currently which just had a multiple hours outage.

@eed3si9n if you add credentials I will add the pull request and then we should cut a 0.3 release.

- [x] Tell scala steward

**Comment by eed3si9n** [comment]
I released it - https://github.com/sbt/sbt-sdlc/releases/tag/v0.3.0

**Comment by eed3si9n** [comment]
Notified it as well - https://github.com/scala-steward-org/scala-steward/pull/3028
